//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciserver_webService.casjobs {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.Cas.jhu.edu", ConfigurationName="casjobs.JobsSoap")]
    public interface JobsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/ExecuteQuickJobOID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteQuickJobOID(string oid, string md5, string qry, string context, string taskname, bool isSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/ExecuteQuickJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteQuickJob(long wsid, string pw, string qry, string context, string taskname, bool isSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/ExecuteQuickJobDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteQuickJobDS(long wsid, string pw, string qry, string context, string taskname, bool isSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/SubmitJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SubmitJob(long wsid, string pw, string qry, string context, string taskname, int estimate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/SubmitJobInto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SubmitJobInto(long wsid, string pw, string qry, string context, string table, string taskname, int estimate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/CancelJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CancelJob(long wsId, string pw, long jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/GetJobStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetJobStatus(long wsId, string pw, long jobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/GetJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sciserver_webService.casjobs.CJJob[] GetJobs(long owner_wsid, string owner_pw, string conditions, bool includeSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/GetJobsJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sciserver_webService.casjobs.Job[] GetJobsJob(long owner_wsid, string owner_pw, string conditions, bool includeSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/GetQueues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sciserver_webService.casjobs.CJQueue[] GetQueues(long wsid, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/GetJobTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sciserver_webService.casjobs.CJType[] GetJobTypes(long wsid, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/SubmitExtractJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long SubmitExtractJob(long wsid, string pw, string tableName, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/UploadData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UploadData(long wsid, string pw, string tableName, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/SetServiceState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SetServiceState(long wsid, string pw, string serviceName, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.Cas.jhu.edu/GetServiceState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetServiceState(long wsid, string pw, string serviceName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.Cas.jhu.edu")]
    public partial class CJJob : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long jobIDField;
        
        private long rowsField;
        
        private long webServicesIDField;
        
        private System.DateTime timeSubmitField;
        
        private System.DateTime timeStartField;
        
        private System.DateTime timeEndField;
        
        private int statusField;
        
        private int queueField;
        
        private string taskNameField;
        
        private string outputLocField;
        
        private string errorField;
        
        private string queryField;
        
        private string contextField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long JobID {
            get {
                return this.jobIDField;
            }
            set {
                this.jobIDField = value;
                this.RaisePropertyChanged("JobID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long WebServicesID {
            get {
                return this.webServicesIDField;
            }
            set {
                this.webServicesIDField = value;
                this.RaisePropertyChanged("WebServicesID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime TimeSubmit {
            get {
                return this.timeSubmitField;
            }
            set {
                this.timeSubmitField = value;
                this.RaisePropertyChanged("TimeSubmit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime TimeStart {
            get {
                return this.timeStartField;
            }
            set {
                this.timeStartField = value;
                this.RaisePropertyChanged("TimeStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime TimeEnd {
            get {
                return this.timeEndField;
            }
            set {
                this.timeEndField = value;
                this.RaisePropertyChanged("TimeEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Queue {
            get {
                return this.queueField;
            }
            set {
                this.queueField = value;
                this.RaisePropertyChanged("Queue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TaskName {
            get {
                return this.taskNameField;
            }
            set {
                this.taskNameField = value;
                this.RaisePropertyChanged("TaskName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OutputLoc {
            get {
                return this.outputLocField;
            }
            set {
                this.outputLocField = value;
                this.RaisePropertyChanged("OutputLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("Query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.Cas.jhu.edu")]
    public partial class CJType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.Cas.jhu.edu")]
    public partial class CJQueue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contextField;
        
        private int timeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
                this.RaisePropertyChanged("Timeout");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.Cas.jhu.edu")]
    public partial class Job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long jobIDField;
        
        private long rowsField;
        
        private long webServicesIDField;
        
        private System.DateTime timeSubmitField;
        
        private System.DateTime timeStartField;
        
        private System.DateTime timeEndField;
        
        private int sendEmailField;
        
        private int statusField;
        
        private int autoCompleteField;
        
        private int estimateField;
        
        private string taskNameField;
        
        private string outputLocField;
        
        private string hostIPField;
        
        private string messageField;
        
        private string queryField;
        
        private string modifiedQueryField;
        
        private string targetField;
        
        private string outputTypeField;
        
        private string paramsField;
        
        private string created_TableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long JobID {
            get {
                return this.jobIDField;
            }
            set {
                this.jobIDField = value;
                this.RaisePropertyChanged("JobID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long WebServicesID {
            get {
                return this.webServicesIDField;
            }
            set {
                this.webServicesIDField = value;
                this.RaisePropertyChanged("WebServicesID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime TimeSubmit {
            get {
                return this.timeSubmitField;
            }
            set {
                this.timeSubmitField = value;
                this.RaisePropertyChanged("TimeSubmit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime TimeStart {
            get {
                return this.timeStartField;
            }
            set {
                this.timeStartField = value;
                this.RaisePropertyChanged("TimeStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime TimeEnd {
            get {
                return this.timeEndField;
            }
            set {
                this.timeEndField = value;
                this.RaisePropertyChanged("TimeEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int SendEmail {
            get {
                return this.sendEmailField;
            }
            set {
                this.sendEmailField = value;
                this.RaisePropertyChanged("SendEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int AutoComplete {
            get {
                return this.autoCompleteField;
            }
            set {
                this.autoCompleteField = value;
                this.RaisePropertyChanged("AutoComplete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Estimate {
            get {
                return this.estimateField;
            }
            set {
                this.estimateField = value;
                this.RaisePropertyChanged("Estimate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TaskName {
            get {
                return this.taskNameField;
            }
            set {
                this.taskNameField = value;
                this.RaisePropertyChanged("TaskName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OutputLoc {
            get {
                return this.outputLocField;
            }
            set {
                this.outputLocField = value;
                this.RaisePropertyChanged("OutputLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string HostIP {
            get {
                return this.hostIPField;
            }
            set {
                this.hostIPField = value;
                this.RaisePropertyChanged("HostIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("Query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ModifiedQuery {
            get {
                return this.modifiedQueryField;
            }
            set {
                this.modifiedQueryField = value;
                this.RaisePropertyChanged("ModifiedQuery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("Target");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string OutputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
                this.RaisePropertyChanged("OutputType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("Params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Created_Table {
            get {
                return this.created_TableField;
            }
            set {
                this.created_TableField = value;
                this.RaisePropertyChanged("Created_Table");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JobsSoapChannel : Sciserver_webService.casjobs.JobsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobsSoapClient : System.ServiceModel.ClientBase<Sciserver_webService.casjobs.JobsSoap>, Sciserver_webService.casjobs.JobsSoap {
        
        public JobsSoapClient() {
        }
        
        public JobsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ExecuteQuickJobOID(string oid, string md5, string qry, string context, string taskname, bool isSystem) {
            return base.Channel.ExecuteQuickJobOID(oid, md5, qry, context, taskname, isSystem);
        }
        
        public string ExecuteQuickJob(long wsid, string pw, string qry, string context, string taskname, bool isSystem) {
            return base.Channel.ExecuteQuickJob(wsid, pw, qry, context, taskname, isSystem);
        }
        
        public System.Data.DataSet ExecuteQuickJobDS(long wsid, string pw, string qry, string context, string taskname, bool isSystem) {
            return base.Channel.ExecuteQuickJobDS(wsid, pw, qry, context, taskname, isSystem);
        }
        
        public long SubmitJob(long wsid, string pw, string qry, string context, string taskname, int estimate) {
            return base.Channel.SubmitJob(wsid, pw, qry, context, taskname, estimate);
        }
        
        public long SubmitJobInto(long wsid, string pw, string qry, string context, string table, string taskname, int estimate) {
            return base.Channel.SubmitJobInto(wsid, pw, qry, context, table, taskname, estimate);
        }
        
        public void CancelJob(long wsId, string pw, long jobId) {
            base.Channel.CancelJob(wsId, pw, jobId);
        }
        
        public int GetJobStatus(long wsId, string pw, long jobId) {
            return base.Channel.GetJobStatus(wsId, pw, jobId);
        }
        
        public Sciserver_webService.casjobs.CJJob[] GetJobs(long owner_wsid, string owner_pw, string conditions, bool includeSystem) {
            return base.Channel.GetJobs(owner_wsid, owner_pw, conditions, includeSystem);
        }
        
        public Sciserver_webService.casjobs.Job[] GetJobsJob(long owner_wsid, string owner_pw, string conditions, bool includeSystem) {
            return base.Channel.GetJobsJob(owner_wsid, owner_pw, conditions, includeSystem);
        }
        
        public Sciserver_webService.casjobs.CJQueue[] GetQueues(long wsid, string pw) {
            return base.Channel.GetQueues(wsid, pw);
        }
        
        public Sciserver_webService.casjobs.CJType[] GetJobTypes(long wsid, string pw) {
            return base.Channel.GetJobTypes(wsid, pw);
        }
        
        public long SubmitExtractJob(long wsid, string pw, string tableName, string type) {
            return base.Channel.SubmitExtractJob(wsid, pw, tableName, type);
        }
        
        public void UploadData(long wsid, string pw, string tableName, string data) {
            base.Channel.UploadData(wsid, pw, tableName, data);
        }
        
        public void SetServiceState(long wsid, string pw, string serviceName, string state) {
            base.Channel.SetServiceState(wsid, pw, serviceName, state);
        }
        
        public string GetServiceState(long wsid, string pw, string serviceName) {
            return base.Channel.GetServiceState(wsid, pw, serviceName);
        }
    }
}
